[colors.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#ffffff"
yellow = "#d19a66"

[colors.normal]
black = "#282c34"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#d19a66"

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[font]
size = 16

[font.bold]
family = "Inconsolata Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Inconsolata Nerd Font Mono"

[font.normal]
family = "Inconsolata Nerd Font Mono"

[font.offset]
y = 4

[shell]
args = ["-l", "-c", "source ~/.zshrc; tmux attach || tmux"]
program = "/bin/zsh"

[window.dimensions]
columns = 256
lines = 64
